import type { Metadata } from 'next';
import { Inter, Indie_Flower, Geist_Mono } from 'next/font/google';
import './globals.css';
import Layout from '@/components/Layout';

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

const indieFlowerSans = Indie_Flower({
  variable: '--font-indier-flower-sans',
  subsets: ['latin'],
  weight: '400',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Comida Di Buteco',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" suppressHydrationWarning={true} data-lt-installed="true">
      <body
        className={`${interSans.variable} ${geistMono.variable} ${indieFlowerSans.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
